/**
 * One-off cleanup after removing the post, person, commissioner, staffMember, department,
 * commissionersPage and staffPage document types, and resetting the page content.
 *
 * Run from the studio directory:
 *   npx sanity exec scripts/cleanupRemovedTypes.ts --with-user-token -- --dry
 *   npx sanity exec scripts/cleanupRemovedTypes.ts --with-user-token
 *
 * DELETES (published and draft versions):
 *   - every `page` document - the pages are being re-authored from scratch;
 *   - every document whose `_type` is no longer in the schema (the removed types above, plus
 *     anything else orphaned). Internal types (sanity.*, system.*, media.*, assist.*) are
 *     never touched.
 *
 * REWRITES, in documents that are kept: any `link` that points at a deleted page becomes a
 * `#` placeholder URL link, keeping its label, so menus survive instead of blocking the delete
 * on a strong reference. Any other reference to a deleted document is removed.
 *
 * Idempotent: a second run finds nothing to do. Assets uploaded for the deleted documents stay
 * in the media library; remove them there if unwanted.
 *
 * Pass --dry to print the plan without writing anything.
 */

import {getCliClient} from 'sanity/cli'

import schema from '../../sanity.schema.json'

const client = getCliClient({apiVersion: '2025-09-25'})
const DRY_RUN = process.argv.includes('--dry')

const INTERNAL_PREFIXES = ['sanity.', 'system.', 'media.', 'assist.']

type Doc = {_id: string; _type: string; [key: string]: unknown}

const publishedId = (id: string) => id.replace(/^drafts\./, '')

/** Rewrites references to deleted ids. Returns the new value and whether anything changed. */
function scrub(value: unknown, deleted: Set<string>): {value: unknown; changed: boolean} {
  if (Array.isArray(value)) {
    let changed = false
    const out: unknown[] = []
    for (const item of value) {
      if (isDeletedRef(item, deleted)) {
        changed = true
        continue
      }
      const r = scrub(item, deleted)
      changed ||= r.changed
      out.push(r.value)
    }
    return {value: out, changed}
  }
  if (value && typeof value === 'object') {
    const obj = {...(value as Record<string, unknown>)}
    let changed = false
    // A link to a deleted page keeps its place as a '#' placeholder.
    if (obj.linkType === 'page' && isDeletedRef(obj.page, deleted)) {
      delete obj.page
      obj.linkType = 'href'
      obj.href = '#'
      changed = true
    }
    for (const [key, child] of Object.entries(obj)) {
      if (isDeletedRef(child, deleted)) {
        delete obj[key]
        changed = true
        continue
      }
      const r = scrub(child, deleted)
      if (r.changed) {
        obj[key] = r.value
        changed = true
      }
    }
    return {value: obj, changed}
  }
  return {value, changed: false}
}

function isDeletedRef(value: unknown, deleted: Set<string>): boolean {
  const ref = (value as {_ref?: unknown} | null)?._ref
  return typeof ref === 'string' && deleted.has(publishedId(ref))
}

async function main() {
  // Read from the extracted schema (regenerated by `npm run sanity:typegen`) rather than imported
  // from src/schemaTypes, which pulls in JSX that sanity exec cannot load.
  const known = new Set(
    (schema as {type: string; name: string}[]).filter((t) => t.type === 'document').map((t) => t.name),
  )
  const all = await client.fetch<Doc[]>(`*[!(_id in path("_.**"))]`)

  const isInternal = (type: string) => INTERNAL_PREFIXES.some((p) => type.startsWith(p))
  const doomed = all.filter((d) => d._type === 'page' || (!known.has(d._type) && !isInternal(d._type)))
  const doomedIds = new Set(doomed.map((d) => d._id))
  const deletedPublished = new Set(doomed.map((d) => publishedId(d._id)))

  const byType = new Map<string, number>()
  for (const d of doomed) byType.set(d._type, (byType.get(d._type) ?? 0) + 1)
  console.log(`${DRY_RUN ? '[dry run] ' : ''}Deleting ${doomed.length} documents:`)
  for (const [type, n] of [...byType].sort()) console.log(`  - ${type}: ${n}`)

  const patches: {id: string; set: Record<string, unknown>; fields: string[]}[] = []
  for (const doc of all) {
    if (doomedIds.has(doc._id)) continue
    const set: Record<string, unknown> = {}
    for (const [key, val] of Object.entries(doc)) {
      if (key.startsWith('_')) continue
      const r = scrub(val, deletedPublished)
      if (r.changed) set[key] = r.value
    }
    if (Object.keys(set).length) patches.push({id: doc._id, set, fields: Object.keys(set)})
  }
  console.log(`Rewriting references in ${patches.length} kept documents:`)
  for (const p of patches) console.log(`  - ${p.id}: ${p.fields.join(', ')}`)

  if (DRY_RUN) return console.log('Dry run - nothing written.')
  if (!doomed.length && !patches.length) return console.log('Nothing to do.')

  const tx = client.transaction()
  for (const p of patches) tx.patch(p.id, (patch) => patch.set(p.set))
  for (const d of doomed) tx.delete(d._id)
  await tx.commit()
  console.log('Done.')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
