/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type CarouselImageImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "carouselImage.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type DownloadFile = {
  asset?: SanityFileAssetReference
  media?: unknown // Unable to locate the referenced type "file.media" in schema
  _type: 'file'
}

export type SocialLink = {
  _type: 'socialLink'
  platform: 'facebook' | 'instagram' | 'linkedin' | 'x' | 'youtube'
  url: string
}

export type InfoLine = {
  _type: 'infoLine'
  text: string
  href?: string
}

export type InfoColumn = {
  _type: 'infoColumn'
  heading: string
  lines: Array<
    {
      _key: string
    } & InfoLine
  >
}

export type MenuLink = {
  _type: 'menuLink'
  label: string
  link: Link
}

export type MenuGroup = {
  _type: 'menuGroup'
  label: string
  children: Array<
    {
      _key: string
    } & MenuLink
  >
}

export type CtaContact = {
  _type: 'ctaContact'
  heading?: string
  body?: string
  button?: Button
  desktopImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  mobileImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  disabled?: boolean
}

export type MissionStatement = {
  _type: 'missionStatement'
  eyebrow?: string
  heading: string
  links?: Array<{
    label: string
    link?: Link
    _type: 'missionLink'
    _key: string
  }>
  disabled?: boolean
}

export type AnchorLinks = {
  _type: 'anchorLinks'
  links?: Array<{
    label: string
    link?: Link
    icon?: 'link' | 'download'
    _type: 'anchorLink'
    _key: string
  }>
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page'
  href?: string
  page?: PageReference
  openInNewTab?: boolean
}

export type ContactForm = {
  _type: 'contactForm'
  heading?: string
  disabled?: boolean
}

export type MapTeaser = {
  _type: 'mapTeaser'
  heading?: string
  body?: string
  disabled?: boolean
}

export type DownloadBlock = {
  _type: 'downloadBlock'
  downloads?: Array<{
    label?: string
    file: DownloadFile
    _type: 'download'
    _key: string
  }>
  disabled?: boolean
}

export type Timeline = {
  _type: 'timeline'
  entries?: Array<{
    year: string
    title: string
    description?: string
    _type: 'timelineEntry'
    _key: string
  }>
  disabled?: boolean
}

export type ImageCarousel = {
  _type: 'imageCarousel'
  eyebrow?: string
  images?: Array<{
    image: CarouselImageImage
    caption?: string
    _type: 'carouselImage'
    _key: string
  }>
  disabled?: boolean
}

export type JumpNavContent = {
  _type: 'jumpNavContent'
  heading?: string
  headingLevel?: 'h1' | 'h2'
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h3' | 'h4' | 'h5' | 'h6'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          {
            _key: string
          } & Link
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
        _key: string
      }
  >
  disabled?: boolean
}

export type BasicLeftRightText = {
  _type: 'basicLeftRightText'
  eyebrow?: string
  heading?: string
  headingLevel?: 'h1' | 'h2'
  buttons?: Array<{
    label: string
    link?: Link
    variant?: 'primary' | 'secondary' | 'ghost'
    _type: 'blockButton'
    _key: string
  }>
  rightContent?: BlockContent
  disabled?: boolean
}

export type HeroTertiary = {
  _type: 'heroTertiary'
  eyebrow?: string
  heading?: string
  headingLevel?: 'h1' | 'h2'
  body?: string
  disabled?: boolean
}

export type HeroSecondary = {
  _type: 'heroSecondary'
  eyebrow?: string
  body?: string
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  variant?: 'lowlands' | 'moody-moor' | 'light-brown'
  disabled?: boolean
}

export type HeroImage = {
  _type: 'heroImage'
  eyebrow: string
  heading: string
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  disabled?: boolean
}

export type Hero = {
  _type: 'hero'
  eyebrow?: string
  heading?: string
  body?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  disabled?: boolean
}

export type HeroVideo = {
  _type: 'heroVideo'
  video: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  poster: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  alt: string
  autoplay?: boolean
  disabled?: boolean
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page'
        href?: string
        page?: PageReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
      _key: string
    }
  | ({
      _key: string
    } & AnchorLinks)
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type Resource = {
  _id: string
  _type: 'resource'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type PropertyType = {
  _id: string
  _type: 'propertyType'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
}

export type PropertyTypeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'propertyType'
}

export type ResourceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'resource'
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  description?: string
  link?: string
  propertyTypes?: Array<
    {
      _key: string
    } & PropertyTypeReference
  >
  resources?: Array<
    {
      _key: string
    } & ResourceReference
  >
  boundaryIds?: Array<string>
  location?: Geopoint
  disablePopup?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type ProjectSettings = {
  _id: string
  _type: 'projectSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  heading?: string
  intro?: string
  boundaryData?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  boundaryIdProperty: string
  trailsData?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  defaultCenter?: Geopoint
  defaultZoom?: number
}

export type MenuReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'menu'
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  newsletterHeading: string
  infoColumns?: Array<
    {
      _key: string
    } & InfoColumn
  >
  footerMenu?: MenuReference
  legalMenu?: MenuReference
  socialLinks?: Array<
    {
      _key: string
    } & SocialLink
  >
  organizationName: string
}

export type Menu = {
  _id: string
  _type: 'menu'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  items: Array<
    | ({
        _key: string
      } & MenuGroup)
    | ({
        _key: string
      } & MenuLink)
  >
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  landingPage?: PageReference
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page'
      href?: string
      page?: PageReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  parent?: PageReference
  pathOnly?: boolean
  pageBuilder?: Array<
    | ({
        _key: string
      } & BasicLeftRightText)
    | ({
        _key: string
      } & ContactForm)
    | ({
        _key: string
      } & CtaContact)
    | ({
        _key: string
      } & DownloadBlock)
    | ({
        _key: string
      } & Hero)
    | ({
        _key: string
      } & HeroImage)
    | ({
        _key: string
      } & HeroSecondary)
    | ({
        _key: string
      } & HeroTertiary)
    | ({
        _key: string
      } & HeroVideo)
    | ({
        _key: string
      } & ImageCarousel)
    | ({
        _key: string
      } & JumpNavContent)
    | ({
        _key: string
      } & MapTeaser)
    | ({
        _key: string
      } & MissionStatement)
    | ({
        _key: string
      } & Timeline)
  >
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | CarouselImageImage
  | SanityFileAssetReference
  | DownloadFile
  | SocialLink
  | InfoLine
  | InfoColumn
  | MenuLink
  | MenuGroup
  | CtaContact
  | MissionStatement
  | AnchorLinks
  | PageReference
  | Link
  | ContactForm
  | MapTeaser
  | DownloadBlock
  | Timeline
  | ImageCarousel
  | JumpNavContent
  | BasicLeftRightText
  | HeroTertiary
  | HeroSecondary
  | HeroImage
  | Hero
  | HeroVideo
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Resource
  | Slug
  | PropertyType
  | PropertyTypeReference
  | ResourceReference
  | Project
  | Geopoint
  | SanityImageCrop
  | SanityImageHotspot
  | ProjectSettings
  | MenuReference
  | Footer
  | Menu
  | Settings
  | Page
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
